# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc-proto/src/main/proto/Mekur.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%grpc-proto/src/main/proto/Mekur.proto\x12\x18\x63om.example.grpcproto.v1\"#\n\x0eStudentRequest\x12\x11\n\tstudentId\x18\x01 \x01(\t\"`\n\x0fStudentResponse\x12\x11\n\tstudentId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08semester\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x65pt\x18\x04 \x01(\t\x12\x0c\n\x04\x63gpa\x18\x05 \x01(\x01\"g\n\x16RegisterStudentRequest\x12\x11\n\tstudentId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08semester\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x65pt\x18\x04 \x01(\t\x12\x0c\n\x04\x63gpa\x18\x05 \x01(\x01\"\\\n\x12\x41llStudentResponse\x12\x46\n\x13studentResponseList\x18\x01 \x03(\x0b\x32).com.example.grpcproto.v1.StudentResponse\"\x0e\n\x0c\x45mptyRequest2\xc0\x03\n\x0eStudentService\x12g\n\x0egetStudentById\x12(.com.example.grpcproto.v1.StudentRequest\x1a).com.example.grpcproto.v1.StudentResponse\"\x00\x12p\n\x0fregisterStudent\x12\x30.com.example.grpcproto.v1.RegisterStudentRequest\x1a).com.example.grpcproto.v1.StudentResponse\"\x00\x12j\n\x11\x64\x65leteStudentById\x12(.com.example.grpcproto.v1.StudentRequest\x1a).com.example.grpcproto.v1.StudentResponse\"\x00\x12g\n\rgetAllStudent\x12&.com.example.grpcproto.v1.EmptyRequest\x1a,.com.example.grpcproto.v1.AllStudentResponse\"\x00\x42\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_proto.src.main.proto.Mekur_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _STUDENTREQUEST._serialized_start=67
  _STUDENTREQUEST._serialized_end=102
  _STUDENTRESPONSE._serialized_start=104
  _STUDENTRESPONSE._serialized_end=200
  _REGISTERSTUDENTREQUEST._serialized_start=202
  _REGISTERSTUDENTREQUEST._serialized_end=305
  _ALLSTUDENTRESPONSE._serialized_start=307
  _ALLSTUDENTRESPONSE._serialized_end=399
  _EMPTYREQUEST._serialized_start=401
  _EMPTYREQUEST._serialized_end=415
  _STUDENTSERVICE._serialized_start=418
  _STUDENTSERVICE._serialized_end=866
# @@protoc_insertion_point(module_scope)
